// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3LqigiyZAiSH2_r8CYer-FHHMg2HBttM',
    appId: '1:945455108126:web:d03d0b1d419640895c9e0f',
    messagingSenderId: '945455108126',
    projectId: 'joev-fintess',
    authDomain: 'joev-fintess.firebaseapp.com',
    storageBucket: 'joev-fintess.firebasestorage.app',
    measurementId: 'G-WF3C1WP5MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLYE2YyC-8ba229aNxHC1BjkIRHkaZVnA',
    appId: '1:945455108126:android:17124a8b9b8a567e5c9e0f',
    messagingSenderId: '945455108126',
    projectId: 'joev-fintess',
    storageBucket: 'joev-fintess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjkt7IMd9T3fAWvxSvWPES5LMWKKspuw',
    appId: '1:945455108126:ios:80cd4c69adc66f225c9e0f',
    messagingSenderId: '945455108126',
    projectId: 'joev-fintess',
    storageBucket: 'joev-fintess.firebasestorage.app',
    iosBundleId: 'com.example.joveTrainer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJjkt7IMd9T3fAWvxSvWPES5LMWKKspuw',
    appId: '1:945455108126:ios:80cd4c69adc66f225c9e0f',
    messagingSenderId: '945455108126',
    projectId: 'joev-fintess',
    storageBucket: 'joev-fintess.firebasestorage.app',
    iosBundleId: 'com.example.joveTrainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3LqigiyZAiSH2_r8CYer-FHHMg2HBttM',
    appId: '1:945455108126:web:db6a9842f130efb15c9e0f',
    messagingSenderId: '945455108126',
    projectId: 'joev-fintess',
    authDomain: 'joev-fintess.firebaseapp.com',
    storageBucket: 'joev-fintess.firebasestorage.app',
    measurementId: 'G-JDR63S3NVK',
  );
}
