name: jove_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.4.5
  firebase_messaging: ^16.4.3
  flutter_svg: ^2.0.10 
  google_fonts: ^8.2.1
  google_sign_in: ^6.2.1
  intl: ^0.20.3
  lottie: ^3.1.0 

  
  slide_to_act: ^2.0.2
  fl_chart: ^1.2.0
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 
flutter:
  uses-material-design: true
  assets:
    - assets/images/landing_photo.png
    - assets/images/sc0.jpg
    - assets/images/sc1.jpg
    - assets/images/sc1.png 
    - assets/images/sc2.jpg 
    - assets/images/sc3.jpg
    - assets/images/sc4.jpg
    - assets/images/sc5.jpg
    - assets/images/kettlebell-icon.svg 
    - assets/images/apps.png
    # It's good practice to declare your new icon assets here too
    - assets/images/rr.png
    - assets/images/appicon.png
    - assets/images/male.png
    - assets/images/female.png


flutter_launcher_icons:
  android: true
  ios: true
  # Used for iOS (Needs a solid white background, with a smaller, padded logo)
  image_path: "assets/images/rr.png" 
  
  # Used for Android
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  # Needs a transparent background, with a smaller, padded logo
  adaptive_icon_foreground: "assets/images/appicon.png"