name: jove_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
    
  # --- LOCALIZATION PACKAGES ---
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.7
  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_storage: ^13.4.6
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.10 
  google_fonts: ^8.2.1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  lottie: ^3.1.0 

  slide_to_act: ^2.0.2
  fl_chart: ^1.2.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.3
  
  # --- NEW: MAPS & GPS LOCATION PACKAGES ---
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  geolocator: ^13.0.1    
  geocoding: ^3.0.0      
  razorpay_flutter: ^1.4.5
  
  # --- NEW: BLUETOOTH BLE PACKAGES ---
  flutter_blue_plus: ^1.34.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 

# --- FORCES FLUTTER TO ACCEPT THE CORRECT VERSIONS ---
dependency_overrides:
  intl: 0.20.2
  http: ^1.2.0
  google_api_headers: ^5.3.7    # <-- MOVED HERE
  package_info_plus: ^10.2.1    # <-- MOVED HERE
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/landing_photo.png
    - assets/images/sc0.jpg
    - assets/images/sc1.jpg
    - assets/images/sc1.png 
    - assets/images/sc2.jpg 
    - assets/images/sc3.jpg
    - assets/images/sc4.jpg
    - assets/images/sc5.jpg
    - assets/images/kettlebell-icon.svg 
    - assets/images/apps.png
    - assets/images/rr.png
    - assets/images/appicon.png
    - assets/images/male.png
    - assets/images/female.png
    - assets/images/loading.gif
    - assets/translations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/rr.png" 
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/appicon.png"