name: jove_trainer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  firebase_messaging: ^16.4.3
  google_fonts: ^6.2.1
  url_launcher: ^6.3.2

  # 👇 ADDED THESE TWO FOR DARK MODE 👇
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # --- LOCALIZATION DEPENDENCIES ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 👇 The Native Splash Screen package 👇
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/landing_photo.png

# 👇 Native Splash Screen Configuration 👇
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/landing_photo.png"
  android_12:
    color: "#ffffff"
    image: "assets/images/landing_photo.png"